### ISSUE TITLE
macOS 12.3 没有 python 命令

### ISSUE THREAD

**Issue by wssgcg1213** [openkraken/node-qjsc#12]
安装的时候会报错

**Comment by cnryb** [comment]
macOS 12.3 移除了 python2 版本。可以用 python3 命令代替。

**Comment by wssgcg1213** [comment]
> macOS 12.3 移除了 python2 版本。可以用 python3 命令代替。

python3 也是默认没有的, 需要 brew 引入, 如果没有引入的用户是引导, 或者能否直接预置 prebuilt?

**Comment by cnryb** [comment]
赞同 prebuild 。
或者是不是可以考虑一下 WebAssembly , 利用 WebAssembly 解除对宿主环境的依赖。

**Comment by wssgcg1213** [comment]
> 赞同 prebuild 。 或者是不是可以考虑一下 WebAssembly , 利用 WebAssembly 解除对宿主环境的依赖。

@andycall 这个方案或许可以研究一下?
